language: android
dist: trusty
sudo: false

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-29

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # System image to run emulator during your tests
    - sys-img-x86-android-29

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

